### PR TITLE
Make model exportable to ONNX (#16)

### PR DESCRIPTION
**Pull request by djvergel**

### CODE REVIEW

**Comment by pawni** [comment]
Thanks for putting this together!

I think this might require a bit more discussion though. For me it isn't quite clear which method should be the forward method on DECI.

I personally would have suggested to either expose `sample` or `log_prob` as a forward method rather than `simulate_sem`. Why did you choose this?

**Comment by additv** [comment]
Hi! Its been a while since I made this change to our internal fork of DECI but I can hopefully shed some light here.

IIRC:
Yes, it also seemed to me like `sample`, or `log_prob` would be good entry points to expose, but for a variety of reasons it seemed like it would require some fairly large changes to get `torch.onnx.export` to run on the DECI object itself.

Instead the goal of this change was to make a minimally invasive change to allow us to get an ONNX export of `DECI.ICGNN` (which is at the core of `sample()`) and then recreate the `sample()` code client-side.

(please forgive me if I got the details wrong here, it's been a while...)

**Comment by additv** [comment]
FYI: One other benefit to adding `forward()` to `ContractiveInvertibleGNN` is that it will allow you to use `torch.jit.script(deci_model.ICGNN)` on it and get some nearly free performance gains.

**Comment by agrinh** [comment]
Thanks for your contribution and the discussion in this PR. We'll be releasing a major revision which will be constructing traditional pytorch modules and be compatible with ONNX exports, so I'm closing this for now. Please feel free to raise issues if there are any particular requests related to ONNX exports in the future.

**Pull request closed without merging**
